//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bootstrapsdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        public int Eid { get; set; }
        public string E_Name { get; set; }
        public string E_Salary { get; set; }
        public string E_Gender { get; set; }
        public string E_DOB { get; set; }
        public Nullable<int> Did { get; set; }
    
        public virtual tbl_dept tbl_dept { get; set; }
    }
}
