//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bootstrapsdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_dept
    {
        public tbl_dept()
        {
            this.tbl_Employee = new HashSet<tbl_Employee>();
        }
    
        public int Did { get; set; }
        public string D_Name { get; set; }
        public string HOD { get; set; }
        public string Gender { get; set; }
    
        public virtual ICollection<tbl_Employee> tbl_Employee { get; set; }
    }
}
